apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: kps
    meta.helm.sh/release-namespace: monitoring
    prometheus-operator-validated: "true"
  name: test-alert
  namespace: monitoring
spec:
  groups:
  - name: prometheus
    rules:
    - alert: test-alert
      annotations:
        description: CPU usage on {{  }} more then 10%
        summary: 
      expr: 'sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job="node-exporter", mode=~"idle|iowait|steal"}[5m]))) / ignoring(cpu) group_left count without (cpu, mode) (node_cpu_seconds_total{job="node-exporter", mode="idle"})) > 0.1'
      for: 10m
      labels:
        severity: critical