apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: kps
    meta.helm.sh/release-namespace: monitoring
    prometheus-operator-validated: "true"
  name: worker-node-cpu-usage
  namespace: monitoring
spec:
  groups:
  - name: prometheus
    rules:
    - alert: WorkerNodeCPUUsage-0
      annotations: 
        description: High cpu usage
        summary: CPU usage on node worker (94.26.229.183) more then 80%
      expr: sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job="node-exporter", mode=~"idle|iowait|steal", instance=~"94.26.229.183:9100"}[30s]))) / ignoring(cpu) group_left count without (cpu, mode) (node_cpu_seconds_total{job="node-exporter", mode="idle", instance=~"94.26.229.183:9100"})) > 0.8
      for: 5s
      labels:
        severity: critical