apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-monitor
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
    - development
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: worker-svc

