name: Build & Push ecs-exporter chart
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/helm-push-action@v2
      env:
        CHART_FOLDER: './'
        CHARTMUSEUM_URL: 'http://94.26.229.183:8080'
        CHARTMUSEUM_USER: 'klin'
        CHARTMUSEUM_PASSWORD: '19120252'
