name: Build & Push ecs-exporter chart
on: push

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Helm Chart to ChartMuseum
        uses: unwrittenmedia/helm3-push-action@v1.0.2
        env:
          SOURCE_DIR: '.'
          CHART_FOLDER: './'
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://museus.bullbenua.ru'
          CHARTMUSEUM_USER: 'klin'
          CHARTMUSEUM_PASSWORD: '19120252'

