name: Build & Push ecs-exporter chart
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push Helm Chart to ChartMuseum
        uses: bsord/helm-push@4.1.0
        with:
          username: 'klin'
          password: '19120252'
          registry-url: 'http://94.26.229.183:8080'
          force: true
          chart-folder: './'


